ReviewFood/Areas/Admin/Controllers/HomeController.cs
using Microsoft.Ajax.Utilities;
using ReviewFood.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ReviewFood.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        db_WebReviewFoodEntities db = new db_WebReviewFoodEntities();
        // GET: Admin/Home
        public ActionResult Index()
        {
            int TongDanhMucCha = db.DanhMucChas.Count();
            int TongDanhMuc = db.DanhMucs.Count();
            int TongTinTuc = db.BaiViets.Count();
            int TongTinChuaDuyet = db.BaiViets.Where(tt => tt.TrangThai == false).Count();
            int TaiKhoanChuaDuyet = db.TaiKhoans.Where(ttk => ttk.TrangThai == false).Count();
            int TongTaiKhoan = db.TaiKhoans.Count();
            int TongDanhGias = db.DanhGias.Count();
            int[] data = new int[] { TongDanhMucCha, TongDanhMuc, TongTinTuc, TongTaiKhoan, TongTinChuaDuyet, TaiKhoanChuaDuyet, TongDanhGias };
            ViewBag.Data = data;
            return View();
        }
    }
}

ReviewFood/Controllers/BaiVietController.cs
using ReviewFood.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace ReviewFood.Controllers
{
    public class BaiVietController : Controller
    {
        db_WebReviewFoodEntities db = new db_WebReviewFoodEntities();
        // GET: BaiViet
        public ActionResult Index(int id = 0)
        {
            if (TempData["Done"] != null || TempData["Error"] != null)
            {
                ViewBag.Done = TempData["Done"];
                ViewBag.Error = TempData["Error"];
                TempData.Remove("Done");
                TempData.Remove("Error");
            }
            var data = db.BaiViets.Find(id);
            if (data == null)
            {
                return RedirectToAction("Index", "Home");
            }
            object comments = (from cmt in db.DanhGias
                               join tt in db.BaiViets on cmt.IdTinTuc equals tt.Id
                               join tk in db.TaiKhoans on cmt.IdTaiKhoan equals tk.Id
                               where cmt.IdTinTuc == id && cmt.TrangThai == true
                               orderby cmt.NgayTao descending
                               select new DanhGia_BaiViet
                               {
                                   Id = cmt.Id,
                                   NoiDung = cmt.NoiDung,
                                   BaiViet = tt.TieuDe,
                                   TaiKhoan = tk.HoTen,
                                   NgayTao = cmt.NgayTao,
                                   NgaySua = cmt.NgaySua,
                                   TrangThai = cmt.TrangThai
                               }).ToList();
            ViewBag.Comments = comments;
            return View(data);
        }

        public ActionResult Search(string keywork = "", int page = 1)
        {
            var TinTucs = (from tt in db.BaiViets
                           join dm in db.DanhMucs on tt.IdDanhMuc equals dm.Id
                           orderby tt.Id descending
                           where tt.TieuDe.Contains(keywork) || tt.NoiDung.Contains(keywork)
                           select new BaiViet_DanhMuc
                           {
                               DanhMuc = dm.TenDanhMuc,
                               MaDanhMuc = dm.Id,
                               MaTinTuc = tt.Id,
                               TieuDe = tt.TieuDe,
                               NgayTao = tt.NgayTao,
                               HinhAnh = tt.HinhAnh
                           }).ToPagedList(page, 12);
            return View(TinTucs);
        }
        public ActionResult Create()
        {
            ViewBag.DanhMucs = db.DanhMucs.ToList();
            return View();
        }

        // POST: Admin/BaiViet/Create
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BaiViet baiViet, HttpPostedFileBase img)
        {
            try
            {
                string filename = "";
                if (img != null)
                {
                    filename = Path.GetFileNameWithoutExtension(img.FileName);
                }

                else
                {
                    filename = "";
                }
                if (filename != "")
                {
                    string extension = Path.GetExtension(img.FileName);
                    if (extensionFile(extension) == true)
                    {
                        string fileId = Guid.NewGuid().ToString().Replace("-", "");
                        // tring userId = GetUserId(); Function to get user id based on your schema



                        //file.SaveAs(path);
                        var _filename = filename + extension;
                        filename = filename + extension;
                        filename = Path.Combine(Server.MapPath("~/Assets/Image"), filename);
                        img.SaveAs(filename);
                        baiViet.HinhAnh = _filename;
                    }
                    else
                    {
                        ViewBag.Error = "File không đúng định dạng, hãy điền lại dữ liệu";
                        return View(baiViet);
                    }
                }
                baiViet.TrangThai = false;
                //baiViet.IdTaiKhoan = db.BaiViets.Max(p => p.IdTaiKhoan) + 1;
                baiViet.NgayTao = DateTime.Now;
                baiViet.NgaySua = DateTime.Now;
                db.BaiViets.Add(baiViet);
                db.SaveChanges();
                ViewBag.Done = "Thêm bài viết thành công, xin chờ duyệt";
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
            }
            ViewBag.DanhMucs = db.DanhMucs.ToList();
            return View(baiViet);
        }
        public bool extensionFile(string extension)
        {
            var st_Exten = extension.ToLower();
            switch (st_Exten)
            {
                case ".jpg":
                    return true;
                case ".jpeg":
                    return true;
                case ".png":
                    return true;
                case ".gif":
                    return true;
                case ".veg":
                    return true;
                default:
                    return false;
            }
        }
    }
}

ReviewFood/Controllers/DanhGiaController.cs
using ReviewFood.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ReviewFood.Controllers
{
    public class DanhGiaController : Controller
    {
        db_WebReviewFoodEntities db = new db_WebReviewFoodEntities();
        // GET: DanhGia
        public ActionResult Create(string cMessage, int MaTinTuc)
        {
            var session = Session["TaiKhoan"];
            if (session == null)
            {
                TempData["Error"] = "Bạn phải đăng nhập";
                return Redirect("/BaiViet/Index/" + MaTinTuc);
            };
            string data = Session["TaiKhoan"].ToString();
            string[] Account = new string[3];
            Account = (data != null) ? data.Split(',') : Account;
            //if (id == int.Parse(Account[2]))
            //{
            //    Session.Remove("TaiKhoan");
            //    return RedirectToAction("Index", "Login");
            //}
            DanhGia cmt = new DanhGia();
            cmt.NoiDung = cMessage;
            cmt.IdTinTuc = MaTinTuc;
            cmt.IdTaiKhoan = int.Parse(Account[2]);
            cmt.NgayTao = DateTime.Now;
            cmt.NgaySua = DateTime.Now;
            cmt.TrangThai = true;
            db.DanhGias.Add(cmt);
            db.SaveChanges();
            return Redirect("/BaiViet/Index/" + MaTinTuc);
        }
    }
}

ReviewFood/Controllers/DanhMucChaController.cs
using PagedList;
using ReviewFood.Areas.Admin.Controllers;
using ReviewFood.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ReviewFood.Controllers
{
    public class DanhMucChaController : Controller
    {
        db_WebReviewFoodEntities db = new db_WebReviewFoodEntities();
        // GET: DanhMuc
        public ActionResult Index(int page = 1, int id = 0)
        {
            var data = db.DanhMucChas.Find(id);
            var datas = db.DanhMucs.Find(id);
            if (data == null)
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.Title = data.TenDM;
            var TinTucs = (from tt in db.BaiViets
                           join dmc in db.DanhMucChas on tt.IdDMCha equals dmc.MaDMCha
                           join dm in db.DanhMucs on tt.IdDanhMuc equals dm.Id
                           orderby tt.Id descending
                           where tt.TrangThai == true
                           where tt.IdDanhMuc == id
                           where dmc.MaDMCha == id
                           select new BaiViet_DanhMucCha
                           {
                               
                               NoiDung = tt.NoiDung,
                               MaDMCha = dmc.MaDMCha,
                               DanhMuc = dm.TenDanhMuc,
                               MaDanhMuc = dm.Id,
                               MaTinTuc = tt.Id,
                               TieuDe = tt.TieuDe,
                               NgayTao = tt.NgayTao,
                               HinhAnh = tt.HinhAnh
                           }).ToPagedList(page, 12);

            //ViewBag.Titles = datas.TenDanhMuc;
            //var TinTucw = (from tt in db.BaiViets
            //               join dm in db.DanhMucs on tt.IdDanhMuc equals dm.Id
            //               orderby tt.Id descending
            //               where tt.TrangThai == true
            //               where tt.IdDanhMuc == id
            //               select new BaiViet_DanhMuc
            //               {
            //                   DanhMuc = dm.TenDanhMuc,
            //                   MaDanhMuc = dm.Id,
            //                   MaTinTuc = tt.Id,
            //                   TieuDe = tt.TieuDe,
            //                   NgayTao = tt.NgayTao,
            //                   HinhAnh = tt.HinhAnh
            //               }).Take(10);
            return View(TinTucs);
        }
    }
}

ReviewFood/Controllers/DanhMucController.cs
using ReviewFood.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ReviewFood.Controllers
{
    public class DanhMucController : Controller
    {
        db_WebReviewFoodEntities db = new db_WebReviewFoodEntities();
        // GET: DanhMuc
        public ActionResult Index(int page = 1, int id = 0)
        {
            var data = db.DanhMucs.Find(id);
            if (data == null)
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.Title = data.TenDanhMuc;
            var TinTucs = (from tt in db.BaiViets
                           join dm in db.DanhMucs on tt.IdDanhMuc equals dm.Id
                           orderby tt.Id descending
                           where tt.TrangThai == true
                           where tt.IdDanhMuc == id
                           select new BaiViet_DanhMuc
                           {
                               DanhMuc = dm.TenDanhMuc,
                               MaDanhMuc = dm.Id,
                               MaTinTuc = tt.Id,
                               TieuDe = tt.TieuDe,
                               NgayTao = tt.NgayTao,
                               HinhAnh = tt.HinhAnh
                           }).ToPagedList(page, 12);
            return View(TinTucs);
        }
    }
}

ReviewFood/Controllers/HomeController.cs
using ReviewFood.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ReviewFood.Controllers
{
    public class HomeController : Controller
    {
        db_WebReviewFoodEntities db = new db_WebReviewFoodEntities();
        public ActionResult Index()
        {
            var featured = (from tt in db.BaiViets
                            join dm in db.DanhMucs on tt.IdDanhMuc equals dm.Id
                            //join user in db.TaiKhoans on tt.IdTaiKhoan equals user.Id 
                            where tt.TrangThai == true
                            orderby tt.Id descending
                            select new BaiViet_DanhMuc
                            {
                                DanhMuc = dm.TenDanhMuc,
                                MaDanhMuc = dm.Id,
                                MaTinTuc = tt.Id,
                                TieuDe = tt.TieuDe,
                                NgayTao = tt.NgayTao,
                                HinhAnh = tt.HinhAnh,
                                //IdUser = user.HoTen 
                            }).Take(3);
            ViewBag.Featured = featured;

            ViewBag.TopTen = (from tt in db.BaiViets
                              join dm in db.DanhMucs on tt.IdDanhMuc equals dm.Id
                              //join user in db.TaiKhoans on tt.IdTaiKhoan equals user.Id 
                              where tt.TrangThai == true
                              orderby tt.Id descending
                              select new BaiViet_DanhMuc
                              {
                                  DanhMuc = dm.TenDanhMuc,
                                  MaDanhMuc = dm.Id,
                                  MaTinTuc = tt.Id,
                                  TieuDe = tt.TieuDe,
                                  NgayTao = tt.NgayTao,
                                  HinhAnh = tt.HinhAnh,
                                  //IdUser = user.HoTen 
                              }).Take(10);
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [ChildActionOnly]
        public ActionResult MenuView()
        {
            var menu = db.DanhMucChas.ToList();
            return PartialView(menu);
        }
    }
}

ReviewFood/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Home Page";
    var Count = ViewBag.Data as int[];
    ViewData["TitleHeader"] = "Thống kê chung";
}
<div class="row">
    <div class="row col-md-12">
        <div class="col-md-3">
            <div class="card card-sm-3">
                <div class="card-icon bg-info">
                    <i class="ion ion-ios-paper"></i>
                </div>
                <div class="card-wrap">
                    <div class="card-header">
                        <h4><a href="@Url.Action("Index", "DanhMucCha")">Tổng số Danh mục cha</a></h4>
                    </div>
                    <div class="card-body">
                        @Count[0]
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card card-sm-3">
                <div class="card-icon bg-info">
                    <i class="ion ion-ios-paper"></i>
                </div>
                <div class="card-wrap">
                    <div class="card-header">
                        <h4><a href="@Url.Action("Index", "DanhMuc")">Tổng số Danh mục</a></h4>
                    </div>
                    <div class="card-body">
                        @Count[1]
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card card-sm-3">
                <div class="card-icon bg-info">
                    <i class="ion ion-ios-paper-outline"></i>
                </div>
                <div class="card-wrap">
                    <div class="card-header">
                        <h4><a href="@Url.Action("Index", "BaiViet")">Tổng số Tin tức</a></h4>
                    </div>
                    <div class="card-body">
                        @Count[2]
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card card-sm-3">
                <div class="card-icon bg-danger">
                    <i class="ion ion-alert"></i>
                </div>
                <div class="card-wrap">
                    <div class="card-header">
                        <h4><a href="@Url.Action("TinChuaDuyet", "BaiViet")">Tổng số Tin Chưa Duyệt</a></h4>
                    </div>
                    <div class="card-body">
                        @Count[4]
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card card-sm-3">
                <div class="card-icon bg-success">
                    <i class="ion ion-person"></i>
                </div>
                <div class="card-wrap">
                    <div class="card-header">
                        <h4><a href="@Url.Action("Index", "TaiKhoan")">Tổng số tài khoản</a></h4>
                    </div>
                    <div class="card-body">
                        @Count[3]
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card card-sm-3">
                <div class="card-icon bg-warning">
                    <i class="ion ion-person"></i>
                </div>
                <div class="card-wrap">
                    <div class="card-header">

                        <h4><a href="@Url.Action("ChuaDuyetTK", "TaiKhoan")">Tổng số Tài Khoản bị khóa</a></h4>
                    </div>
                    <div class="card-body">
                        @Count[5]
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card card-sm-3">
                <div class="card-icon bg-success">
                    <i class="ion ion-reply-all"></i>
                </div>
                <div class="card-wrap">
                    <div class="card-header">
                        <h4><a href="@Url.Action("tongtkDanhGia", "DanhGia")">Tổng số Tài Khoản đánh giá</a></h4>
                    </div>
                    <div class="card-body">
                        @Count[6]
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="hello">
        <br />
        <br />
        <br />
        <div class="col-12">
            <div class="display-2">Welcome to Website Admin</div>
            <hr />
        </div>
    </div>

</div>